### ISSUE TITLE
Lesson 08 exercise isn't rendering

### ISSUE THREAD

**Issue by bryanbraun** [chenkie/try-graphql#6]
When I browse to the exercise for lesson 8 (and lesson 9) the exercise window is blank and I'm not able to interact with it.

I'm using Chrome as my browser, version 83.0.4103.106.

Here's what I see:

![image](https://user-images.githubusercontent.com/1256329/85078778-2fe3f980-b193-11ea-90f0-61ca3b7c871f.png)

It looks like there are errors in the javascript console, which could help with debugging. Here's the error output:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Module.<anonymous> (https://c.staticblitz.com/assets/client-353697bf962c9a68bc21b.js:2:2879646)
    at a (https://c.staticblitz.com/assets/client-353697bf962c9a68bc21b.js:2:561)
    at n (https://c.staticblitz.com/assets/client-353697bf962c9a68bc21b.js:2:430)
    at https://c.staticblitz.com/assets/client-353697bf962c9a68bc21b.js:2:1536
    at https://c.staticblitz.com/assets/client-353697bf962c9a68bc21b.js:2:1540
client-353697bf962c9a68bc21b.js:2 Uncaught Error: Could not find store registered with name 'appStore'. Registered store names include [  ]. Maybe you forgot to register the store?
    at Object.getStoreGenerator (client-353697bf962c9a68bc21b.js:2)
    at Object.getStoreGenerator (client-353697bf962c9a68bc21b.js:2)
    at d (client-353697bf962c9a68bc21b.js:2)
    at client-353697bf962c9a68bc21b.js:2
    at p (client-353697bf962c9a68bc21b.js:2)
    at g (client-353697bf962c9a68bc21b.js:2)
    at HTMLDocument.<anonymous> (client-353697bf962c9a68bc21b.js:2)
3client-353697bf962c9a68bc21b.js:2 Uncaught Error: There are no stores hydrated and you are requesting the store appStore.
This can happen if you are server rendering and either:
1. You do not call redux_store near the top of your controller action's view (not the layout)
   and before any call to react_component.
2. You do not render redux_store_hydration_data anywhere on your page.
    at Object.getStore (client-353697bf962c9a68bc21b.js:2)
    at Object.getStore (client-353697bf962c9a68bc21b.js:2)
    at je (client-353697bf962c9a68bc21b.js:2)
    at client-353697bf962c9a68bc21b.js:2
4client-353697bf962c9a68bc21b.js:2 Uncaught Error: There are no stores hydrated and you are requesting the store appStore.
This can happen if you are server rendering and either:
1. You do not call redux_store near the top of your controller action's view (not the layout)
   and before any call to react_component.
2. You do not render redux_store_hydration_data anywhere on your page.
    at Object.getStore (client-353697bf962c9a68bc21b.js:2)
    at Object.getStore (client-353697bf962c9a68bc21b.js:2)
    at je (client-353697bf962c9a68bc21b.js:2)
    at client-353697bf962c9a68bc21b.js:2
```

**Comment by chenkie** [comment]
Hmm looks like issues coming from StackBlitz. I'm able to get it to render, but the output in StackBlitz has some issues it looks like.
<img width="1242" alt="Screen Shot 2020-06-19 at 4 20 50 PM" src="https://user-images.githubusercontent.com/1847678/85176906-e8b84000-b248-11ea-9c01-f5613963ca94.png">
